[project]
name = "universal-test-runner"
version = "0.8.0"

authors = [{ name = "David Brownman", email = "oss@xavd.id" }]
description = "Universal, language-aware unit test runner."
readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Testing",
]
keywords = ["testing", "test-runner", "pytest"]

dependencies = ["click==8.1.3", "colorama==0.4.6"]

[project.urls]
"Homepage" = "https://github.com/xavdid/universal-test-runner"
"Bug Tracker" = "https://github.com/xavdid/universal-test-runner/issues"
"Author" = "https://xavd.id"
"Changelog" = "https://github.com/xavdid/universal-test-runner/blob/main/CHANGELOG.md"

[project.scripts]
t = "universal_test_runner.runner:run"
universal-test-runner = "universal_test_runner.cli:cli"

[dependency-groups]
dev = [
  { include-group = "test" },
  { include-group = "lint" },
  "tox>=4.32.0",
  "tox-uv>=1.29.0",
]
test = ["pytest==9.1.1", "responses==0.23.1"]
lint = ["pyright==1.1.414", "ruff==0.16.8"]

[build-system]
requires = ["uv_build>=0.12.17,<0.13"]
build-backend = "uv_build"

[tool.ruff.lint]
extend-select = [
  "E",    # PEP8 recommendations
  "F",    # bugs
  "I001", # import sorting
  "BLE",  # catching root Exception
  "A",    # built-in shadowing
  "C4",   # unnecessary comprehensions
  "ISC",  # implicit string concat
  "PIE",  # misc useful lints
  "Q",    # better quoting behavior
  "RSE",  # no parens on exceptions that lack args
  "RET",  # more correct return behavior
  "SIM",  # general style things
  "TC",   # type-only imports should be in a typecheck block
  "ARG",  # unused args
  "PTH",  # use pathlib
  "FLY",  # short "".join calls
  "PERF", # performance hints
  "PL",   # pylint, general recommendations
]

extend-ignore = [
  "E501",    # skip enforcing line length
  "E741",    # ignore short variable names
  "PLR2004", # magic values
  "PLR0911", # too many returns
  "PLR0912", # too many branches
  "PLR0913", # too many arguments
  "PLR0915", # too many statements
  "Q000",    # single quotes; handled by formatter
]

unfixable = [
  "F401", # don't remove unused imports; annoying while editing
  # run `just lint --fix --fixable F401` to fix these manually
  "F841", # don't remove unused variables
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "PLR0917", # max positional args; I can't control how many fixtures I need
]
